version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  apt_packages:
  - optipng
  - libxcb-cursor0
  - xvfb
  jobs:
    post_create_environment:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs --no-cache
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
