# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    permissions: write-all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
      DISPLAY: :99
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Ubuntu dependecies
      run: |
        sudo apt-get update
        sudo apt-get install freeglut3-dev

    - name: Install xvfb on Ubuntu
      run: |
        sudo apt-get install xvfb
        nohup Xvfb $DISPLAY &

    - name: Install Poetry
      run: pipx install poetry

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: poetry

    - name: Install Differt2D
      run: |
        poetry install --with docs,github-action

    - name: Build docs
      run: cd docs && poetry run make html

    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-pages-artifact@v2
      with:
        # Upload docs/build/html dir
        path: docs/build/html/

    - name: Deploy to GitHub Pages
      id: deployment
      if: github.event_name != 'pull_request'
      uses: actions/deploy-pages@v2
