name: Upload Python Package

on:
  push:

  release:
    types: [published]

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rye
      env:
        RYE_INSTALL_OPTION: --yes
      run: |
        curl -sSf https://rye.astral.sh/get | bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH

    - name: Configure Rye
      run: rye config --set-bool behavior.use-uv=true

    - name: Build package
      run: rye build

    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish
